"""Add level column to users

Revision ID: 61116e0953f6
Revises: 70631934e67f
Create Date: 2025-10-09 02:58:09.902377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61116e0953f6'
down_revision = '70631934e67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
